### ISSUE TITLE
Make bigger measuring acrylic for checking how long the bit stick out

### ISSUE THREAD

**Issue by Siemenc** [fellesverkstedet/workshop-wiki#9]
One that can measure up to 60 mm

**Comment by JensDyvik** [comment]
The original measuring acrylic was made by [Alex Scaub](https://github.com/uomou) as a gift from a visiting Fab Lab user in 2017. Maybe he still has the original file? :)

**Comment by Siemenc** [comment]
Had some time today to fix this. Will publish file

![IMG_20201020_155235](https://user-images.githubusercontent.com/10272127/96604331-49d64a00-12f5-11eb-891e-199813f012f7.jpg)
